apiVersion: v1
kind: ServiceAccount
metadata:
  name: confluence
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: confluence
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: wiki
        k8s-app: confluence
    spec:
      serviceAccountName: confluence
      containers:
      - name: confluence
        image: atlassian/confluence-server
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/var/atlassian/application-data/confluence"
          name: confluence
      volumes:
      - name: confluence
        persistentVolumeClaim:
          claimName: confluence-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: wiki
  name: confluence
  namespace: default
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    k8s-app: confluence
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rbd

