apiVersion: v1
kind: ServiceAccount
metadata:
  name: jira
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: project
        k8s-app: jira
    spec:
      serviceAccountName: jira
      containers:
      - name: jira
        image: atlassianfan/jira
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/opt/atlassian/jira-home"
          name: jira
      volumes:
      - name: jira
        persistentVolumeClaim:
          claimName: jira-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: project
  name: jira
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    k8s-app: jira
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rbd

